import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = process.cwd()
const htmlPath = resolve(root, 'dist/index.html')
let html = await readFile(htmlPath, 'utf8')

const cssPath = html.match(/href="(\/assets\/[^"]+\.css)"/)?.[1]
const jsPath = html.match(/src="(\/assets\/[^"]+\.js)"/)?.[1]

if (!cssPath || !jsPath) {
  throw new Error('Could not locate the built CSS and JavaScript assets')
}

const [css, javascript, favicon] = await Promise.all([
  readFile(resolve(root, 'dist', cssPath.slice(1)), 'utf8'),
  readFile(resolve(root, 'dist', jsPath.slice(1)), 'utf8'),
  readFile(resolve(root, 'dist/favicon.svg')),
])

html = html
  .replace(/<link rel="stylesheet"[^>]+>/, `<style>${css.replaceAll('</style', '<\\/style')}</style>`)
  .replace(
    /<script type="module"[^>]+><\/script>/,
    `<script type="module">${javascript.replaceAll('</script', '<\\/script')}</script>`,
  )
  .replace(
    'href="/favicon.svg"',
    `href="data:image/svg+xml;base64,${favicon.toString('base64')}"`,
  )

await writeFile(
  resolve(root, 'worker/static.generated.ts'),
  `// Generated by scripts/embed-assets.mjs. Do not edit.\nexport const INDEX_HTML_BASE64 = ${JSON.stringify(Buffer.from(html).toString('base64'))}\n`,
)
